# Generated by Django 3.2.12 on 2023-04-19 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=24, verbose_name='Номер бокса')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость аренды в сутки')),
                ('is_stored', models.BooleanField(default=False, verbose_name='Занято')),
                ('width', models.IntegerField(verbose_name='Ширина (см)')),
                ('height', models.IntegerField(verbose_name='Высота (см)')),
                ('depth', models.IntegerField(verbose_name='Глубина (см)')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='storage.storage')),
            ],
            options={
                'verbose_name': 'Бокс',
                'verbose_name_plural': 'Боксы',
            },
        ),
    ]
