# Generated by Django 3.2.12 on 2023-04-19 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='depth',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Глубина (см)'),
        ),
        migrations.AlterField(
            model_name='box',
            name='height',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Высота (см)'),
        ),
        migrations.AlterField(
            model_name='box',
            name='width',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ширина (см)'),
        ),
    ]
