# Generated by Django 3.2.12 on 2023-04-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20230419_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
