# Generated by Django 3.2.12 on 2023-04-19 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_storage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='building',
            field=models.CharField(blank=True, max_length=20, verbose_name='Дом/корпус'),
        ),
        migrations.AddField(
            model_name='storage',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='storage',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='storage',
            name='specificity',
            field=models.CharField(blank=True, max_length=100, verbose_name='Особенность'),
        ),
        migrations.AddField(
            model_name='storage',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='Улица'),
        ),
        migrations.CreateModel(
            name='StorageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото склада')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='storage.storage')),
            ],
        ),
    ]
