# Generated by Django 3.2.12 on 2023-04-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20230419_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storageimage',
            options={'verbose_name': 'Фото склада', 'verbose_name_plural': 'Фото складов'},
        ),
    ]
