# Generated by Django 3.2.12 on 2023-04-20 18:20

from django.db import migrations, models
import storage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_alter_storageimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='celsius_temperature',
            field=models.IntegerField(blank=True, null=True, verbose_name='Температура в Цельсиях'),
        ),
        migrations.AddField(
            model_name='storage',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[storage.validators.thumbnail_image_restriction], verbose_name='Миниатюра'),
        ),
    ]
