# Generated by Django 3.2.12 on 2023-04-21 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_auto_20230420_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='is_stored',
        ),
    ]
