# Generated by Django 3.2.12 on 2023-04-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_remove_box_is_stored'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальное кол-во боксов'),
        ),
    ]
