# Generated by Django 3.2.12 on 2023-04-19 06:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость аренды в сутки')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активна'), ('CLOSED', 'Завершена'), ('EXPIRED', 'Просрочена')], max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало аренды')),
                ('expired_at', models.DateTimeField(verbose_name='Окончание аренды')),
                ('closed_at', models.DateTimeField(verbose_name='Завершена')),
                ('box', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rents', to='storage.box', verbose_name='Бокс')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
            },
        ),
    ]
