# Generated by Django 3.2.12 on 2023-04-19 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0001_initial'),
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='personal_account.client', verbose_name='Арендатор'),
            preserve_default=False,
        ),
    ]
