# Generated by Django 3.2.12 on 2023-04-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0002_rent_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершена'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активна'), ('CLOSED', 'Завершена'), ('EXPIRED', 'Просрочена')], default='ACTIVE', max_length=20, verbose_name='Статус'),
        ),
    ]
