# Generated by Django 3.2.12 on 2023-04-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0003_auto_20230419_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='warning_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Предупреждение отправлено'),
        ),
    ]
