# Generated by Django 3.2.12 on 2023-04-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0002_alter_client_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватар'),
        ),
    ]
