# Generated by Django 3.2.12 on 2023-04-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0003_client_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='utm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Рекламный источник'),
        ),
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Аватар'),
        ),
    ]
