# Generated by Django 3.2.12 on 2023-04-21 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0004_auto_20230421_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='utm',
        ),
    ]
